name: Conditional job example
on: 
  push:
    branches:
      - "*" 
jobs:
  always-run:
    runs-on: ubuntu-latest
    steps:
     - run: echo "This job always run"
  
  only-on-main-job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     - run: echo "This job runs on main branche"
